<a href="https://colab.research.google.com/github/syed-khader/learning-python-libraries/blob/main/my_numpy_classwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy(Numerical Python)

* It is a open source library of python used for mathematical and scientific computation.

* Numpy deals with array.

* Numpy is based on C language


In Python we already have list but it has some analytical problem due to its limitation.


1. List can store hetrogenous data as well as homogenous data.But in analytical data like- (Age,Salary,Height,etc) should be stored in same format.

2. List are slow and consumes more memory.
    * list stores the value in a form linked list which makes it slow.

3. List cannot perform mathematical operation like addition,subtraction,division etc on the values. For that we need to write a program

To solve these problems NumPy arrays were introduced.


* It is used because it helps to work with millions of number data.

* It also helps in scientific computation.

* Data analysis

* Statistical operations




In [ ]:
'''
To use Numpy we need to install it
Syntax--> pip install numpy

Numpy basically deals with Arrays
'''

'\nTo use Numpy we need to install it\nSyntax--> pip install numpy\n\nNumpy basically deals with Arrays\n'

# Array

* Array is a collection of homogenous data items stored in a continous memory allocation.

* Array is amutable datatype but we cannot chnage the size. ie the values can be modified but cannot be removed or added.

### Difference between array and list

Array-
1. Array is collection homogenous data items
2. Array is faster
3. Array is contious memory
4. It belongs to Numpy
5. We can perform mathematical operation easily.

List-
1. List is a collection of homogenous and hetrogenous.
2. List is slower
3. discontinued memory
4. It belongs to python
5. we cannot perform mathemtical operations
  easily.



In [ ]:
import numpy as np

## Creating array

In [ ]:
'''
Before creating array we need to import Numpy into the file
Syntax--> import numpy as np



To creae array syntax-->
                np.array(coll)
'''
list_arr=np.array([1,2,3,4])
tup_arr=np.array((10,20,30))
set_arr=np.array({4,5,6})
str_arr=np.array('Sam')
dict_arr=np.array({1:2,3:4})

arr=np.array([True,False,9,8.3,2+6j])
arr

array([1. +0.j, 0. +0.j, 9. +0.j, 8.3+0.j, 2. +6.j])

In [ ]:
'''
Incase we give a hetrogenous data Numpy will convert it into homogenous based on datatype priroity
Bool
integer
float
complex
str
set(object)
dict(object)

Highest pririoty is given to object

We cannot store list or tuple inside the array

'''


'\nIncase we give a hetrogenous data Numpy will convert it into homogenous based on datatype priroity\nBool\ninteger\nfloat\ncomplex\nstr\nset(object)\ndict(object)\n\nHighest pririoty is given to object\n\nWe cannot store list or tuple inside the array\n\n'

In [ ]:
arr=np.array([1,2,3,4])
arr.dtype #used to check the datatype of the values inside array

dtype('int64')

In [ ]:
'''
Array can have n dimensions but majorly they are categorized into 3 types
  1. 1D array
  2. 2D array
  3. 3D array/Multi Dimensional array

1.  1D array
-------------

-> An array with a single colum of data
    np.array([va1,val2,...,valn])

2. 2D array
------------
-> An array which is having rows and columns.
-> These can also be treated as a collection 1D arrays.

np.array([[va1,val2,...,valn],
          [val1,val2,...,valn],
          .
          .
          .
          [val1,val2,...,valn]])

3D array
--------
-> An array which consist of blocks,rows,columns as values
-> it is also treated as collection 2D arrays

np.array([[[va1,val2,...,valn],
          [val1,val2,...,valn],
          [val1,val2,...,valn]],

          [[va1,val2,...,valn],
          [val1,val2,...,valn],
          [val1,val2,...,valn]]])
'''
arr1=np.array([1,2,3,4,5])
arr1

arr2=np.array([[1,2,3,4],
              [5,6,7,8],
               [9,10,11,12]])

arr2

arr3=np.array([[[1,2,3,4],[5,6,7,8]],
               [[9,10,11,12],[13,14,15,16]]])

arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [ ]:
#Syntax to check the dimension of the array
#Syntax-->  arr.ndim

arr1.ndim
arr2.ndim
arr3.ndim

# syntax to check the size/no of elements in an array
#Syntax-->arr.size
# print(arr1)
# arr1.size

# print(arr2)
# arr2.size

# print(arr3)
# arr3.size

#Syntax to check the size of each dimension
# Syntax--> arr.shape

arr1.shape
arr2.shape
arr3.shape
arr3

#Syntax to check the size of the element/item in array
#Syntax--> arr.itemsize

arr1.itemsize
arr2.itemsize
arr3.itemsize
arr4=np.array(['Sam','Rakhi'])
arr4
arr4.itemsize

arr1.itemsize

ar1=np.array([1,2,3])


In [ ]:
'''
Attributes of array

1. ndim-->to check the dimension
2. size--> to get total no of values present inside array
3. dtype-->used to check the datatype of the item in array
4. shape-->to get the size of each dimension
5. itemsize-->to get the byte space of the item
6. nbytes---> to get the total bytespace of the array
'''


'\nAttributes of array\n\n1. ndim-->to check the dimension\n2. size--> to get total no of values present inside array\n3. dtype-->used to check the datatype of the item in array\n4. shape-->to get the size of each dimension\n5. itemsize-->to get the byte space of the item\n6. nbytes---> to get the total bytespace of the array\n'

In [ ]:
'''
Inbuilt function of the array

1.arange()--> it is used to create a array of  sequence of numbers within
given range in  1D.
Syntax-->  np.arange(sv,ev+-1,step)

2.reshape()--> it is used to change the shape of an array from 1D to ND
Syntax--> arr.reshape(shape)


->The product of the shape should always be equal to the size
  of the array

3. zeros()--> it is used to create an  nD array with zeros as value.
->It gives the value in floating numbers.
Syntax-->np.zeros(shape)

4.ones()--> it is used to create nD array with values as 1\
-> the values will be in floating numbers
Syntax-->np.ones((shape))

5. full()--> it is used to create an nD array with a specific value
Syntax-->np.full(shape,n), where n is the value
-> This gives integer values

6. identity()--> it is used to create a 2D identity matrix
-> It gives in floating numbers
Syntax-->np.identity(n), where n--> no of rows and column

7.linspace()->it is used to create an array with equally spaced values
within the given range.
Syntax-->np.linspace(sv,ev,n) where n is the no of values,
                              ev is also included

linspace() always gives value in floating numbers


8.transpose()-->it is used to convert the rows into columns and columns
                to rows
Syntax-->arr.transpose()
'''
# np.identity(4)

# arr=np.arange(1,61).reshape(4,3,5)
# arr
# np.zeros((3,4,5,3))     #4D ARRAY WITH ALL VALUES AS ZERO

np.ones((2,3,4))

np.full((3,4,5),20)

ar=np.linspace(1,10,100)


print(arr2)
print()
print(arr2.transpose())


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### Random Functions On array

In [ ]:


# -> To use any any random function we need to import random module
# Syntax-->import random

In [ ]:
import random

In [ ]:
#rand()--> It is used to generate a nD array with random numbers
#           within 0-1.
#Syntax-->np.random.rand(shape)

np.random.rand(2,3,10)

#randn()--> It is used to generate a ND array with random numbers
#           within normal distribution.
# Syntax--> np.random.randn(shape)

np.random.randn(2,3,4)

#randint()-> it is used to generate random integers values within the
#             given range.
#syntax--> np.random.randint(sv,ev,n)

np.random.randint(-10,10,50)


#choice()--> it is used to choose a random value from the array
#Syntax--> np.random.choice(arr,size)
# -> It works only with 1D array

np.random.choice(arr1,3)


#shuffle()--> it is used to ramndomly place the arrays in order.
#Syntax-->np.random.shuffle(arr)
# -> It will affect original array

np.random.shuffle(arr2)
arr2

#permutation()--> it is used to ramndomly place the values of array
#syntax-->np.permutation(arr)
# -> It will not affect original array
arr1
np.random.permutation(arr1)

#seed()-->It is used to fix the random valuer by giving a
#         starting state
# Syntax--> np.random.seed(n), where n--> starting state


np.random.seed(0)
np.random.randint(1,10,10)

# uniform()-->It is used to get random values in a uniform distribution
#Syntax-->np.random.uniform(sv,ev,n), where n--> no of random values

np.random.uniform(2,10,100)



array([9.13418401, 9.70930208, 5.06753215, 8.3338003 , 6.23115936,
       6.54435649, 9.40477311, 2.56828847, 2.6970344 , 2.16174718,
       8.66095876, 8.22525401, 8.96009719, 9.82894674, 8.39326851,
       5.6918349 , 8.24423341, 2.94619541, 7.11936817, 3.1468263 ,
       9.55735134, 6.17478657, 5.31729552, 4.1164449 , 8.19386952,
       5.64920266, 6.54747159, 2.1503184 , 6.94108398, 6.89676578,
       6.93547197, 9.54998463, 7.45456239, 4.8760632 , 5.49625563,
       7.58104957, 2.48180377, 7.33413372, 7.36510296, 3.68306049,
       3.03141038, 4.52342681, 4.90968617, 6.56157416, 5.50881211,
       9.9069907 , 2.81635849, 3.67101405, 3.29047614, 7.2248666 ,
       4.02633282, 5.73048618, 3.95540474, 3.27175667, 2.88300113,
       7.25063672, 3.10546361, 3.57265889, 4.94980137, 8.56794584,
       2.77681021, 8.70355926, 2.76878726, 9.81167572, 5.74920961,
       9.81408871, 6.83876416, 7.91410864, 2.31350234, 4.2624557 ,
       2.96157249, 4.36912158, 2.94982175, 4.54386544, 5.31410

In [ ]:
'''
1. arange()--> generates a 1D array in sequential manner
2. reshape()--> converts 1D array to Nd array
3. zeros()--> create and ND array with 0 as values
4. ones()---> creates a ND array with 1 as values
5. full()--> creates an ND array with specific value
6. identity()--> cretes a identity with nXn
7. linspace()--> create an array with eaqual difference
8. transpose()--> converts the rows to columns in array
Random Function

1.rand()---> random floating numbrs between 0-1
2. randn()--> random floating numbers between normal distribution
3. randint()--> random integers within given range
4. choice()--> selects random values from the array
5. shuffle()--> shuffles the array in random order and return a view
6. permutation()--> shuffles the array in random order and return a copy.
9. seed()--> fix the random values by giving starting state
10. uniform()--> gives random values in uniform distribution
'''

'\n1. arange()--> generates a 1D array in sequential manner\n2. reshape()--> converts 1D array to Nd array\n3. zeros()--> create and ND array with 0 as values\n4. ones()---> creates a ND array with 1 as values\n5. full()--> creates an ND array with specific value\n6. identity()--> cretes a identity with nXn\n7. linspace()--> create an array with eaqual difference\n8. transpose()--> converts the rows to columns in array\n\nRandom Function\n\n1.rand()---> random floating numbrs between 0-1\n2. randn()--> random floating numbers between normal distribution\n3. randint()--> random integers within given range\n4. choice()--> selects random values from the array\n5. shuffle()--> shuffles the array in random order and return a view\n6. permutation()--> shuffles the array in random order and return a copy.\n9. seed()--> fix the random values by giving starting state\n10. uniform()--> gives random values in uniform distribution\n'