<a href="https://colab.research.google.com/github/syed-khader/learning-python-libraries/blob/main/numpyforgithub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy(Numerical Python)

* It is a open source library of python used for mathematical and scientific computation.

* Numpy deals with array.

* Numpy is based on C language


In Python we already have list but it has some analytical problem due to its limitation.


1. List can store hetrogenous data as well as homogenous data.But in analytical data like- (Age,Salary,Height,etc) should be stored in same format.

2. List are slow and consumes more memory.
    * list stores the value in a form linked list which makes it slow.

3. List cannot perform mathematical operation like addition,subtraction,division etc on the values. For that we need to write a program

To solve these problems NumPy arrays were introduced.


* It is used because it helps to work with millions of number data.

* It also helps in scientific computation.

* Data analysis

* Statistical operations




In [ ]:
'''
To use Numpy we need to install it
Syntax--> pip install numpy

Numpy basically deals with Arrays
'''

'\nTo use Numpy we need to install it\nSyntax--> pip install numpy\n\nNumpy basically deals with Arrays\n'

# Array

* Array is a collection of homogenous data items stored in a continous memory allocation.

* Array is amutable datatype but we cannot chnage the size. ie the values can be modified but cannot be removed or added.

### Difference between array and list

Array-
1. Array is collection homogenous data items
2. Array is faster
3. Array is contious memory
4. It belongs to Numpy
5. We can perform mathematical operation easily.

List-
1. List is a collection of homogenous and hetrogenous.
2. List is slower
3. discontinued memory
4. It belongs to python
5. we cannot perform mathemtical operations
  easily.



In [ ]:
import numpy as np

## Creating array

In [ ]:
'''
Before creating array we need to import Numpy into the file
Syntax--> import numpy as np



To creae array syntax-->
                np.array(coll)
'''
list_arr=np.array([1,2,3,4])
tup_arr=np.array((10,20,30))
set_arr=np.array({4,5,6})
str_arr=np.array('Sam')
dict_arr=np.array({1:2,3:4})

arr=np.array([True,False,9,8.3,2+6j])
arr

array([1. +0.j, 0. +0.j, 9. +0.j, 8.3+0.j, 2. +6.j])

In [ ]:
'''
Incase we give a hetrogenous data Numpy will convert it into homogenous based on datatype priroity
Bool
integer
float
complex
str
set(object)
dict(object)

Highest pririoty is given to object

We cannot store list or tuple inside the array

'''


'\nIncase we give a hetrogenous data Numpy will convert it into homogenous based on datatype priroity\nBool\ninteger\nfloat\ncomplex\nstr\nset(object)\ndict(object)\n\nHighest pririoty is given to object\n\nWe cannot store list or tuple inside the array\n\n'

In [ ]:
arr=np.array([1,2,3,4])
arr.dtype #used to check the datatype of the values inside array

dtype('int64')

In [ ]:
'''
Array can have n dimensions but majorly they are categorized into 3 types
  1. 1D array
  2. 2D array
  3. 3D array/Multi Dimensional array

1.  1D array
-------------

-> An array with a single colum of data
    np.array([va1,val2,...,valn])

2. 2D array
------------
-> An array which is having rows and columns.
-> These can also be treated as a collection 1D arrays.

np.array([[va1,val2,...,valn],
          [val1,val2,...,valn],
          .
          .
          .
          [val1,val2,...,valn]])

3D array
--------
-> An array which consist of blocks,rows,columns as values
-> it is also treated as collection 2D arrays

np.array([[[va1,val2,...,valn],
          [val1,val2,...,valn],
          [val1,val2,...,valn]],

          [[va1,val2,...,valn],
          [val1,val2,...,valn],
          [val1,val2,...,valn]]])
'''
arr1=np.array([1,2,3,4,5])
arr1

arr2=np.array([[1,2,3,4],
              [5,6,7,8],
               [9,10,11,12]])

arr2

arr3=np.array([[[1,2,3,4],[5,6,7,8]],
               [[9,10,11,12],[13,14,15,16]]])

arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [ ]:
#Syntax to check the dimension of the array
#Syntax-->  arr.ndim

arr1.ndim
arr2.ndim
arr3.ndim

# syntax to check the size/no of elements in an array
#Syntax-->arr.size
# print(arr1)
# arr1.size

# print(arr2)
# arr2.size

# print(arr3)
# arr3.size

#Syntax to check the size of each dimension
# Syntax--> arr.shape

arr1.shape
arr2.shape
arr3.shape
arr3

#Syntax to check the size of the element/item in array
#Syntax--> arr.itemsize

arr1.itemsize
arr2.itemsize
arr3.itemsize
arr4=np.array(['Sam','Rakhi'])
arr4
arr4.itemsize

arr1.itemsize

ar1=np.array([1,2,3])


# Attributes of Array

In [ ]:
'''
Attributes of array

1. ndim-->to check the dimension
2. size--> to get total no of values present inside array
3. dtype-->used to check the datatype of the item in array
4. shape-->to get the size of each dimension
5. itemsize-->to get the byte space of the item
6. nbytes---> to get the total bytespace of the array
'''


'\nAttributes of array\n\n1. ndim-->to check the dimension\n2. size--> to get total no of values present inside array\n3. dtype-->used to check the datatype of the item in array\n4. shape-->to get the size of each dimension\n5. itemsize-->to get the byte space of the item\n6. nbytes---> to get the total bytespace of the array\n'

# Inbuilt functions to create array

In [ ]:
'''
Inbuilt function of the array

1.arange()--> it is used to create a array of  sequence of numbers within
given range in  1D.
Syntax-->  np.arange(sv,ev+-1,step)

2.reshape()--> it is used to change the shape of an array from 1D to ND
Syntax--> arr.reshape(shape)


->The product of the shape should always be equal to the size
  of the array

3. zeros()--> it is used to create an  nD array with zeros as value.
->It gives the value in floating numbers.
Syntax-->np.zeros(shape)

4.ones()--> it is used to create nD array with values as 1\
-> the values will be in floating numbers
Syntax-->np.ones((shape))

5. full()--> it is used to create an nD array with a specific value
Syntax-->np.full(shape,n), where n is the value
-> This gives integer values

6. identity()--> it is used to create a 2D identity matrix
-> It gives in floating numbers
Syntax-->np.identity(n), where n--> no of rows and column

7.linspace()->it is used to create an array with equally spaced values
within the given range.
Syntax-->np.linspace(sv,ev,n) where n is the no of values,
                              ev is also included

linspace() always gives value in floating numbers


8.transpose()-->it is used to convert the rows into columns and columns
                to rows
Syntax-->arr.transpose()

9. fill()--> It is used to fill the array with a specific value
Syntax--> arr.fill(value)
'''
# np.identity(4)

# arr=np.arange(1,61).reshape(4,3,5)
# arr
# np.zeros((3,4,5,3))     #4D ARRAY WITH ALL VALUES AS ZERO

np.ones((2,3,4))

np.full((3,4,5),20)

ar=np.linspace(1,10,100)


# print(arr2)
# print()
# print(arr2.transpose())

arr1.fill(9)
arr1


array([9, 9, 9, 9, 9])

### Random Functions On array

In [ ]:


# -> To use any any random function we need to import random module
# Syntax-->import random

In [ ]:
import random

In [ ]:
#rand()--> It is used to generate a nD array with random numbers
#           within 0-1.
#Syntax-->np.random.rand(shape)

np.random.rand(2,3,10)

#randn()--> It is used to generate a ND array with random numbers
#           within normal distribution.
# Syntax--> np.random.randn(shape)

np.random.randn(2,3,4)

#randint()-> it is used to generate random integers values within the
#             given range.
#syntax--> np.random.randint(sv,ev,n)

np.random.randint(-10,10,50)


#choice()--> it is used to choose a random value from the array
#Syntax--> np.random.choice(arr,size)
# -> It works only with 1D array

np.random.choice(arr1,3)


#shuffle()--> it is used to ramndomly place the arrays in order.
#Syntax-->np.random.shuffle(arr)
# -> It will affect original array

np.random.shuffle(arr2)
arr2

#permutation()--> it is used to ramndomly place the values of array
#syntax-->np.permutation(arr)
# -> It will not affect original array
arr1
np.random.permutation(arr1)

#seed()-->It is used to fix the random valuer by giving a
#         starting state
# Syntax--> np.random.seed(n), where n--> starting state


np.random.seed(0)
np.random.randint(1,10,10)

# uniform()-->It is used to get random values in a uniform distribution
#Syntax-->np.random.uniform(sv,ev,n), where n--> no of random values

np.random.uniform(2,10,100)



array([9.13418401, 9.70930208, 5.06753215, 8.3338003 , 6.23115936,
       6.54435649, 9.40477311, 2.56828847, 2.6970344 , 2.16174718,
       8.66095876, 8.22525401, 8.96009719, 9.82894674, 8.39326851,
       5.6918349 , 8.24423341, 2.94619541, 7.11936817, 3.1468263 ,
       9.55735134, 6.17478657, 5.31729552, 4.1164449 , 8.19386952,
       5.64920266, 6.54747159, 2.1503184 , 6.94108398, 6.89676578,
       6.93547197, 9.54998463, 7.45456239, 4.8760632 , 5.49625563,
       7.58104957, 2.48180377, 7.33413372, 7.36510296, 3.68306049,
       3.03141038, 4.52342681, 4.90968617, 6.56157416, 5.50881211,
       9.9069907 , 2.81635849, 3.67101405, 3.29047614, 7.2248666 ,
       4.02633282, 5.73048618, 3.95540474, 3.27175667, 2.88300113,
       7.25063672, 3.10546361, 3.57265889, 4.94980137, 8.56794584,
       2.77681021, 8.70355926, 2.76878726, 9.81167572, 5.74920961,
       9.81408871, 6.83876416, 7.91410864, 2.31350234, 4.2624557 ,
       2.96157249, 4.36912158, 2.94982175, 4.54386544, 5.31410

In [ ]:
_='''
1. arange()--> generates a 1D array in sequential manner
2. reshape()--> converts 1D array to Nd array
3. zeros()--> create and ND array with 0 as values
4. ones()---> creates a ND array with 1 as values
5. full()--> creates an ND array with specific value
6. identity()--> cretes a identity with nXn
7. linspace()--> create an array with eaqual difference
8. transpose()--> converts the rows to columns in array

Random Function

1.rand()---> random floating numbrs between 0-1
2. randn()--> random floating numbers between normal distribution
3. randint()--> random integers within given range
4. choice()--> selects random values from the array
5. shuffle()--> shuffles the array in random order and return a view
6. permutation()--> shuffles the array in random order and return a copy.
9. seed()--> fix the random values by giving starting state
10. uniform()--> gives random values in uniform distribution
'''

In [ ]:
#Wap to transpose a square matrix

l=[[1,2,3],
  [4,5,6],
  [7,8,9]]

for i in range(len(l)):
  for j in range(i+1,len(l)):
    l[i][j],l[j][i]=l[j][i],l[i][j]
for i in l:
  print(i)

[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [ ]:
#flatten()--> It is used to convert ND array to 1D array
#arr.flatten()
#-> It will create a copy and does not affect original array
arr=np.arange(1,25).reshape(2,3,4)
flat=arr.flatten()
flat

#ravel()--> It is used to convert ND array to 1D array
#Syntax-->arr.ravel()
#-> It will create view and affects the original array
#    when any modification are done to ravel

rav=arr.ravel()
# flat[0]=29
# flat
# arr

rav[0]=45
rav
arr

array([[[45,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
#view()--> It is used to copy the array into another variable
#->        It shares the same memory.
#          Modification done in view variable affects the original array


#copy()--> It is used to copy the array into another variable
#           It does not shares same memory
#           Modification done in copy variable does not affects
#            the original array.

vieww=arr1.view()
vieww[2]=36
vieww

arr1
cop=arr1.copy()
cop[-1]=40
cop
arr1

array([ 9,  9, 36,  9,  9])

In [ ]:
# Create a 5 × 5 matrix of random integers between 1 and 100, then reshape it into a 1D array.
arr=np.random.randint(1,100,25).reshape(5,5)
arr.flatten()

# Generate 50 equally spaced values from 0 to 100, then reshape them into a 10 × 5 matrix.
np.linspace(0,100,50).reshape(10,5)
# Create a 6 × 6 matrix filled with ones, then replace it with a matrix filled with 9
#  without creating a new variable.
ar=np.ones((6,6))
ar.fill(9)
ar
# Generate a 4 × 4 matrix of random integers (1–20), then create another 4 × 4 matrix
#  filled with zeros.
ar1=np.random.randint(1,20,16)
ar2=np.zeros((4,4))
# Create an identity matrix of size 8 × 8, then reshape it into a 1D array and
# determine its total number of elements.
np.identity(8).flatten().size


64

# Indexing in array

In [ ]:
'''
Indexing
-> A phenomenom of extracting values from the array using index position

1D indexing-->var[index]

2D indexing-->var[row index,col index]

3D indexing-->var[block index,row index,col index]
'''

'\nIndexing\n-> A phenomenom of extracting values from the array using index position\n\n1D indexing-->var[index]\n\n2D indexing-->var[row index,col index]\n\n3D indexing-->var[block index,row index,col index]\n'

In [ ]:
arr1=np.array([23,65,45,12,34,98
])

arr1[1]

arr2[1,2]

arr3[-1,-1,0]
arr=np.arange(20,80,3).reshape(4,5)
#53,29,77,65,56,32,[65,68,71,74,77]
arr[2,1]
arr[0,-2]
arr[-1,-1]
arr[0]

arr3=np.arange(1,61).reshape(3,4,5)
arr3
#55,43, [16, 17, 18, 19, 20],[[41, 42, 43, 44, 45],
#                              [46, 47, 48, 49, 50],
#                              [51, 52, 53, 54, 55],
#                              [56, 57, 58, 59, 60]]

arr3[-1,2,-1]
arr3[-1,0,2]
arr3[0,-1]
arr3[-1]

array([[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60]])

# Boolean Masking

In [ ]:
'''
Boolean Indexing--> It is a phenomenom of extracting the values from the
            array based on boolean condition.

Syntax--> arr[condition]

-> Incase of 2D boolean indexing or 3D boolean indexing result willbe in
  1D.


'''

'\nBoolean Indexing--> It is a phenomenom of extracting the values from the\n            array based on boolean condition.\n\nSyntax--> arr[condition]\n\n-> Incase of 2D boolean indexing or 3D boolean indexing result willbe in\n  1D.\n\n\n'

In [ ]:
sales=np.array([12000,34000,90000,2000,6000,11000,160000])
sales
#Sales above 10000
sales[sales>10000]


#sales greater than 2000 and less than 15000
sales[(sales>2000) & (sales<15000)]

#sales greater than 7000 and less than 20000
sales[(sales>7000)&(sales<20000)]

#sales greater than 10k or less than 90000
sales[(sales>10000)|(sales<90000)]

num=np.array([34,23,11,76,93,57,73,87,50,92])
#values greater than 50
num[num>50]

#values greater than 2 or less than 100
num[(num>2) | (num<100)]
#even numbers
num[num%2==0]

#odd numbers and multiple of 3
num[(num%2!=0) & (num%3==0)]

#even numbers 10-80
num[(num%2==0) & ((num>10) &(num<=80))]

#numbers between 30-80
num[(num>30) & (num<=80)]



array([34, 76, 57, 73, 50])

In [ ]:
arr2[arr2>8]

array([ 9, 10, 11, 12])

In [ ]:
# Modification of the values using index position
#   Syntax--> arr[index]=new val

print(arr1)
arr1[1]=500
print(arr1)

[23 65 45 12 34 98]
[ 23 500  45  12  34  98]


# Slicing in array

In [ ]:
#Slicing-->Phenomenom of extracting the part of the array using index
#          position

'''
There are 3 types slicing
    1. 1D slicing
    2. 2D slicing
    3. 3D slicing/Mulitdimensional slicing
'''

#1D Slicing
#Syntax--> arr[si:ei+-1:step]

arr1[:]

arr1=np.arange(2,16)
arr1
#last 5 elements
arr1[-5:]
#starting 6 elements
arr1[:6]
#even indes position
arr1[::2]
#[4,7,10,13]
arr1[2::3]
#[15,14,13]
arr1[:-4:-1]


#2D slicing
#Syntax-->arr[row slice,col slice]

#[[6,7,8],[2,3,4]]
arr2[1:,1:]

#[[9,12],[1,4]]
arr2[::2,::3]

#[[4,3,2],[8,7,6]]
arr2[:-3:-1,:-4:-1]

arr2[::-1,::-1]
arr2
# [[9,10][1,2]]
arr2[0:2:1,0:2:1]

# [[12][8][4]]
arr2[::1,-1:-2:-1]

# [[9,10,11,12]]
arr2[0:1:1,::1]
# [[4],[8],[12]]
arr2[::-1,-1:-2:-1]

# [[8,6][12,10]]
arr2[1::-1,::-2]
# [[8]]
arr2[1:2,-1:-2:-1]

ar2=np.arange(1,21).reshape(4,5)
ar2
#[[15,14,13],[10,9,8],[5,4,3]]
ar2[-2::-1,-1:-4:-1]

#[[2,4],[7,9],[12,14]]
ar2[:3,1::2]

#[16, 17, 18, 19, 20]
ar2[3]
#[5,10,15,20]
ar2[::,-1]
#[[3],[8],[13],[18]]
ar2[::,2:3]
#[[5,4],[10,9],[15,14],[20,19]]
ar2[::,-1:-3:-1]

ar2[2::-1,-1:-4:-1]


#3D slicing
#Syntax-->arr[block slice,row slice,col slice]

arr3
#[[8,9,10],[18,19,20]],[[28,29,30][38,39,40]]
arr3[:2,1::2,2::1]

arr3[::,::3,::4]

#[[[5,10,15,20]],[[25,30,35,40]]]

#[[[6,8,10][16,18,20]],[[46,48,50][56,58,60]]]

ar3=np.arange(1,28).reshape(3,3,3)
#[[27,26],[24,23],[21,20]]
#[15,14,13]
#[[[10,11]],[[1,2]]]

In [ ]:
#[[5,10,15,20]],[25,30,35,40]]
arr3[:2,:,-1]

#[[[6,8,10][16,18,20]],[[46,48,50][56,58,60]]]
arr3[::2,1::2,::2]

array([[[ 6,  8, 10],
        [16, 18, 20]],

       [[46, 48, 50],
        [56, 58, 60]]])

In [ ]:
ar3
#[[27,26],[24,23],[21,20]]
ar3[-1,::-1,-1:-3:-1]

#[15,14,13]
ar3[1,1,::-1]

#[[[10,11]],[[1,2]]]
ar3[1::-1,:1,:2]


array([[[10, 11]],

       [[ 1,  2]]])

# Vecotrization (Operation on array)

In [ ]:
#Vectorization of array:
#->To perform mathematical operations on array

#1. Array to array operation
'''
-> To perform array to array operation atleast we should have
    two arrays.
-> The shape of the arrays should be same
-> It will perform the operation element be element
Syntax--> arr1___arr2
'''

#Arithmetic operator--> performs algebric operations

ar1=np.array([1,2,3,4])
ar2=np.array([6,7,8,4])

ar1+ar2
ar1-ar2
ar1*ar2
ar1%ar2
ar1/ar2
ar1//ar2
ar1**ar2

#Relational operator--> compares two arrays
ar1>ar2
ar1>=ar2
ar1<ar2
ar1<=ar2
ar1==ar2
ar1!=ar2

#Logical operator--> compares based on logical operators

#all()--> return True if all values are nonzero
#any()--> return True if any one value is nonzero
ar1=np.array([1,2,0,4])

#Logical and
ar1.all() and ar2.all()
ar1.any() and ar2.any()
ar1.any() and ar2.all()

#Logical or
ar1.all() or ar2.all()
ar1.any() and ar2.any()
ar1.any() and ar2.all()

#Logical not
not ar1.all()
not ar1.any()
not ar2.all()

False

In [ ]:
#Assigment Operators---> assigns array to
ar1+=ar2
ar1-=ar2
ar1*=ar2
# ar1/=ar2
ar1//=ar2
ar1%=ar2
ar1**=ar2
# ar1/=ar2

In [ ]:
ar1=np.array([1,2,0,4])
ar2=np.array([6,7,8,4])

In [ ]:
# bitwise operator--> it performs operation on bits
print(ar1)
print(ar2)
ar1 & ar2 #bitwise and
ar1|ar2 #bitwise or
~ar1 #bitwise not
ar1^ar2 #bitwise xor
ar1<<ar2 #bitwise leftshift
ar1>>ar2 # bitwise rightshift



#membership operator--> checks weather the values is an object of the array
6 in ar1
0 in ar1
ar1 in ar2
ar1 not in ar2
6 not in ar1
0 not in ar1

# identity operator--> it checks if the both the arrays are pointing to the same memory location
ar1 is ar2
ar1 is not ar2

[1 2 0 4]
[6 7 8 4]


True

In [ ]:
# array to constant operations
# --> it perfroms operation on a constant value to the array
# --> here the constant value perfroms operation on each and every salary
#--> of the array and returns an array
sal=np.array([1000,3500,2900,1500])

#employee recieves a puja bonus of 10% of thier salary
sal+sal*0.10


array([1100., 3850., 3190., 1650.])

In [ ]:
# aggregate functions
#--> sum()--> add all the elements of the array.
#syntax--> np.sum(arr)
np.sum(arr1)

# mean()--> gives the arithmetic average of the array
# syntax--> np.mean(arr)
np.mean(arr1)

# min()--> gives the minimum value from the array
#syntax --> np.min(arr)

np.min(arr1)

# argmin()--> gives the index position of the minimum value present inside the array
#syntax--> np.argmin(arr)
np.argmin(arr1)

# argmax()--> gives the index position of the maximum value present inside the array
#syntax--> np.argmax(arr)
np.argmax(arr1)

# var()--> it returns the variance of the values present inside array
# syntax--> np.var(arr)

# LOW VARIANCE --> CLOSELY PACKED VALUES
# HIGH VARIANCE --> WIDELY SPREAD VALUES
np.var(arr1)

#std()--> gives standard deviation ie average variance value
#syntax--> np.std(arr)
np.std(arr1)

#median()--> sorts the value and gives you the middle value
np.median(arr1)

np.float64(8.5)

In [ ]:
# axis parameters
'''
it specifies the axis on what the array will perfrom the operation of the aggregate function.
axis=0--> performs row by row
axis=1--> perfroms col by col '''
ar=np.arange(1,10).reshape(3,3)
ar.sum(axis=0)
ar.sum(axis=1)

ar5=np.array([1,1,2,3,3,4,5,6,6,6])
np.unique(ar5)#--> gets you the unique values from the array



array([1, 2, 3, 4, 5, 6])

In [ ]:
'''
Employee Salary Analysis


salary = np.array([
25000,
32000,
28000,
45000,
52000,
38000,
60000,
42000,
30000,
55000
])


Find the number of employees.


Find total salary.


Find average salary.


Find minimum salary.


Find maximum salary.

Find employees earning above ₹40,000.


Find employees earning below ₹30,000.


Find salaries between ₹30,000 and ₹50,000.


Count employees earning above ₹40,000.


Find salaries greater than the average.

Calculate the percentage of employees earning above ₹40,000.


Give every employee a 10% increment.

Identify salaries significantly above the average.
'''
salary = np.array([
25000,
32000,
28000,
45000,
52000,
38000,
60000,
42000,
30000,
55000
])

# Find the number of employees.
salary.size
# Find total salary.
salary.sum()

# Find average salary.
salary.mean()

# Find minimum salary.
salary.min()

# Find maximum salary.
salary.max()

# Find employees earning above ₹40,000.

salary[salary>40000]

# Find employees earning below ₹30,000.
salary[salary<30000]

# Find salaries between ₹30,000 and ₹50,000.
salary[(salary>30000)&(salary<50000)]
# Count employees earning above ₹40,000.
salary[salary>40000].size

# Find salaries greater than the average.
salary[salary>salary.mean()]
# Calculate the percentage of employees earning above ₹40,000.
(salary[salary>40000].size/salary.size)*100
# Give every employee a 10% increment.
salary+salary*0.10
# Identify salaries significantly above the average.
salary[salary>salary.mean()]

array([27500., 35200., 30800., 49500., 57200., 41800., 66000., 46200.,
       33000., 60500.])

In [85]:
'''
sales = np.array([
[12000, 15000, 18000, 21000],
[22000, 25000, 28000, 30000],
[10000, 14000, 16000, 19000],
[30000, 32000, 35000, 38000]
])


Assume:


Rows → Stores
Columns → Week 1–4
Level 1


Find the shape.


Find Store 1.


Find Week 2 sales.


Find Store 3, Week 4 sales.


Find the first two stores.


Level 2


Calculate total sales.


Calculate sales per store.


Calculate sales per week.


Find average sales.


Find maximum sales.


Level 3


Find all sales above ₹25,000.


Find all sales below ₹15,000.


Find sales between ₹15,000 and ₹30,000.


Count sales greater than ₹25,000.


Find stores whose total sales exceed ₹90,000.'''

sales = np.array([
[12000, 15000, 18000, 21000],
[22000, 25000, 28000, 30000],
[10000, 14000, 16000, 19000],
[30000, 32000, 35000, 38000]
])

# Find the shape.
sales.shape

# Find Store 1.
sales[0]

# Find Week 2 sales.
sales[:,1]

# Find Store 3, Week 4 sales.
sales[2:3,-1]

# Find the first two stores.
sales[:2]

# Level 2


# Calculate total sales.
sales.size

# Calculate sales per store.
sales.sum(axis=1)

# Calculate sales per week.
sales.sum(axis=0)

# Find average sales.
sales.mean()

# Find maximum sales
sales.max()

# Level 3


# Find all sales above ₹25,000.
sales[sales>25000]

# Find all sales below ₹15,000.
sales[sales<15000]

# Find sales between ₹15,000 and ₹30,000.
sales[(sales>15000)&(sales<30000)]

# Count sales greater than ₹25,000.

sales[sales>25000]
# Find stores whose total sales exceed ₹90,000.
sales[sales.sum(axis=1)>90000]

array([[22000, 25000, 28000, 30000],
       [30000, 32000, 35000, 38000]])